### ISSUE TITLE
Support `viem` in addition to `ethers`

### ISSUE THREAD

**Issue by fionnachan** [OffchainLabs/arbitrum-sdk#273]
```[tasklist]
### Tasks
- [ ] #277 
- [ ] #278 
- [ ] #279 
- [ ] https://github.com/OffchainLabs/arbitrum-sdk/issues/274
- [ ] https://github.com/OffchainLabs/arbitrum-sdk/issues/275
- [ ] https://github.com/OffchainLabs/arbitrum-sdk/issues/276
- [ ] #280
- [ ] #281
```

full guide: https://viem.sh/docs/ethers-migration.html
