### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by spsjvc** [OffchainLabs/arbitrum-sdk#321]
Changes should land into the [v4](https://github.com/OffchainLabs/arbitrum-sdk/tree/v4) branch. The branch should be kept in sync with `main`.

```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-sdk/issues/335
- [ ] (maybe) https://github.com/OffchainLabs/arbitrum-sdk/issues/291
- [ ] (maybe) ditch CommonJS
- [ ] (may not be a breaking change) NodeJS v20
- [ ] check if there are any bridge ui code that needs to be in the sdk and vice versa
- [ ] bump ethers version
- [ ] use generated abi types from contracts packages
- [ ] don't use `signer.provider`
- [ ] viem?
- [ ] L1-to-L3 teleporter (maybe v3?)
```
